### ISSUE TITLE
click on the subject menu isnt working

### ISSUE THREAD

**Issue by faisalmushtaq007** [kirandroid/Education-App-Design#1]
i even checked the HomecategoryItem class but i dont know why isnt it responding to the onTap(){}. please help!

**Comment by kirandroid** [comment]
Yup, there was no additional design so could not make the screens. You can just add a new screen and navigate through the onTap.

**Comment by faisalmushtaq007** [comment]
But how will i differentiate between the categories. How will it know which one i tapped, since there is a single onTap method
